name: 'Release'
description: 'Allows semantic-release to be executed in a monorepo'
inputs:
  entry-point:
    description: 'The directory of the package to release.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
      shell: bash
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_REPO_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
      working-directory: ${{ inputs.entry-point }}
      shell: bash

